server:
  port: 8082

spring:
  application:
    name: postal-service

eureka:
  client:
    enable: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true