server:
  port: 8080

spring:
  application:
    name: user-service

eureka:
  client:
    enable: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
